# Generated by Django 4.2.7 on 2023-12-07 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magazine',
            options={'verbose_name': 'Журнал', 'verbose_name_plural': 'Журналы'},
        ),
    ]
